## Assignment 2 
### Due Date: 26 September 2021, Sunday, 11.00 am

### Example: Basic Numpy

(1) Create a NumPy array with the integers from your birthdate (year,
    month, and day)

(2) Retrieve the year.

(3) Replace the year with the current year.

(4) Create a NumPy array containing every 3rd number from 567 to 890. What is the 8th number in this array?  What is the 15th?

In [1]:
import numpy as np

In [2]:
# 1
a = np.array([1986, 12, 24])

In [3]:
# 2
a[0]

1986

In [4]:
# 3
a[0] = 2021

In [5]:
# 4
a= np.arange(567, 890, 3)
a

array([567, 570, 573, 576, 579, 582, 585, 588, 591, 594, 597, 600, 603,
       606, 609, 612, 615, 618, 621, 624, 627, 630, 633, 636, 639, 642,
       645, 648, 651, 654, 657, 660, 663, 666, 669, 672, 675, 678, 681,
       684, 687, 690, 693, 696, 699, 702, 705, 708, 711, 714, 717, 720,
       723, 726, 729, 732, 735, 738, 741, 744, 747, 750, 753, 756, 759,
       762, 765, 768, 771, 774, 777, 780, 783, 786, 789, 792, 795, 798,
       801, 804, 807, 810, 813, 816, 819, 822, 825, 828, 831, 834, 837,
       840, 843, 846, 849, 852, 855, 858, 861, 864, 867, 870, 873, 876,
       879, 882, 885, 888])

In [6]:
a[8]

591

In [7]:
a[15]

612

### Exercise 1 Basic Numpy

(1) Create an array of 10 random integers, from 0-100.

(2) Find the mean and standard deviation of these numbers.  

(3) Create another array of 10 random integers, from 0-100.

(4) Create a new array whose elements are the average of those from
    each of the previous ones.  

(5) Create an array of 10 random floats, from 0-100.

(6) We would expect the mean to be approaximately 50.  Is it?  What's
    the standard deviation?

(7) What are the min and max values?

In [16]:
a = np.random.randint(0, 101, 10) #1
print(f"Mean of the array {a} is {a.mean()} and Standard Deviation is {a.std()}") #2
b = np.random.randint(0, 101, 10) #3
print("second array:\n", b)
c = (a+b)/2 #4
print(f"new array whose elements are the average of those from each of the previous ones:\n{c}")
d = np.random.uniform(low=0.0, high=100.00000001, size=10) #5
#6
if d.mean()==50:
  print(f"Mean of the array {d} is {d.mean()} and Standard Deviation is {d.std()}")
else: 
  print(f"Mean of the array {d} is not 50, but, {d.mean()} and Standard Deviation is {d.std()}")
print(f"Min and Max values of {d} is {d.min()} and {d.max()} respectively.") #7

Mean of the array [24 81 17 87 88 81 13 22  6 81] is 50.0 and Standard Deviation is 33.98529093593286
second array:
 [54 12 91 84 27 65 31  1 82  1]
new array whose elements are the average of those from each of the previous ones:
[39.  46.5 54.  85.5 57.5 73.  22.  11.5 44.  41. ]
Mean of the array [55.97647538 28.42038943 36.51568938 46.43522494 99.11620471 32.98754559
 68.33977993 17.81566966 33.22570145 84.08431487] is not 50, but, 50.29169953349272 and Standard Deviation is 24.92429065700706
Min and Max values of [55.97647538 28.42038943 36.51568938 46.43522494 99.11620471 32.98754559
 68.33977993 17.81566966 33.22570145 84.08431487] is 17.815669662801984 and 99.11620470799555 respectively.


### Exercise 2 Indexing

(1) Create an array of 20 random integers from 0 to 100.

(2) Find the largest even number.

(3) Find the mean of the odd numbers.

(4) Create a NumPy array from the first and last odd numbers.

(5) Create an array of 20 floats from 0-1,000.

(6) Find the items that are less than the mean.

(7) Find the items less than mean-std.

In [9]:
a = np.random.randint(0, 101, 20) #1

# for #2
even_a = np.array([x for x in a if x%2==0])
print(f"the largest even number in the array {a} is {even_a.max()}")

# for #3
odd_a = np.array([x for x in a if x%2==1])
print(f"the mean of odd number in the array {a} is {odd_a.mean()}")

b = np.arange(odd_a[0], odd_a[-1]) #4

c = np.random.uniform(low=0.0, high=1000.00000001, size=20) #5
print(f"Items that are less than the mean of {c} i.e., ({c.mean()}) are {np.array([x for x in c if x < c.mean()])}") #6
print(f"Items that are less than the mean-std of {c} i.e., ({c.mean()-c.std()}) are {np.array([x for x in c if x < (c.mean()-c.std())])}") #7

the largest even number in the array [23 70  5 48 42 18 48 11 68 23  4 27 17  6 28 98 34 85 57 23] is 98
the mean of odd number in the array [23 70  5 48 42 18 48 11 68 23  4 27 17  6 28 98 34 85 57 23] is 30.11111111111111
Items that are less than the mean of [518.79218911 767.13694008 302.78029574 299.24095461 728.68853565
 952.53886976 863.43882116 928.06145953 957.87546384 399.582443
 459.14977486  66.1606962  825.91778487 557.92598887 351.94291439
 885.51060639 720.66685316 726.05022979 615.78999408  23.9326068 ] i.e., (597.5591710948113) are [518.79218911 302.78029574 299.24095461 399.582443   459.14977486
  66.1606962  557.92598887 351.94291439  23.9326068 ]
Items that are less than the mean-std of [518.79218911 767.13694008 302.78029574 299.24095461 728.68853565
 952.53886976 863.43882116 928.06145953 957.87546384 399.582443
 459.14977486  66.1606962  825.91778487 557.92598887 351.94291439
 885.51060639 720.66685316 726.05022979 615.78999408  23.9326068 ] i.e., (318.04623433836

### Exercise 3 More indexing

(1) Create a NumPy array of 20 random integers from 0-100.

(2) What's the smallest even number greater than the mean?

(3) Show all numbers either < mean-std OR > mean+std.

(4) Show odd numbers < mean and even numbers > mean.

In [10]:
a = np.random.randint(0, 101, 20) #1
print(f"the smallest even number greater than the mean in the array \n \
{a} is {np.array([x for x in a if (x>a.mean() and x%2==0)])[0]}") #2

print(f"all numbers either < mean-std OR > mean+std in the array \n \
{a} is {np.array([x for x in a if (x>a.mean()+a.std() or x<a.mean()-a.std())])}") #3

print(f"odd numbers < mean {a.mean()} and even numbers > mean {a.mean()} in the array \n \
{a} is {np.array([x for x in a if ((x%2==0 and x>a.mean()) or (x%2==1 and x<a.mean()))])}") #4

the smallest even number greater than the mean in the array 
 [82 31 44 74 93 67 58 36  5 86 10 97 61  0 38 16 50 40 28 44] is 82
all numbers either < mean-std OR > mean+std in the array 
 [82 31 44 74 93 67 58 36  5 86 10 97 61  0 38 16 50 40 28 44] is [82 93  5 86 10 97  0 16]
odd numbers < mean 48.0 and even numbers > mean 48.0 in the array 
 [82 31 44 74 93 67 58 36  5 86 10 97 61  0 38 16 50 40 28 44] is [82 31 74 58  5 86 50]


### Exercise 4 Assigning via indexes

(1) Create a NumPy array of 40 random integers, from 0-100.

(2) Find all numbers that are within 1 standard deviation of the mean,
    and set them to be equal to the mean.  Has the mean changed?  Has
    the std changed?

(3) Create another NumPy array of 10 random integers, from 0-100.

(4) Set the item at the even indexes to be equal to the items at the odd
    indexes.  So index 0 will get the value at index 1, etc.


In [11]:
a = np.random.randint(0, 101, 40) #1
print(f"created a numpy array:\n{a}")
prev_a_mean, prev_a_std = a.mean(), a.std()
print(f"original mean and std are {prev_a_mean} and {prev_a_std}")

# for #2
print("checking whether mean changed or the std changed...")
a[(a<a.mean()+a.std()) & (a>a.mean()-a.std())]=a.mean()
if prev_a_mean != a.mean():
  print(f"Mean has changed from {prev_a_mean} to {a.mean()}")
else: print("Mean is same!")
if prev_a_std != a.std():
  print("standard deviation has changed")
else: print("standard deviation is same!")

b = np.random.randint(0, 101, 10) #3
print(f"created a numpy array {b}")
# for #4
for i in range(0, len(b), 2):
  b[i] = b[i+1]
print(f"After processing:\n{b}")

created a numpy array:
[ 3 12  1 18 70 32 36 83  1 13 87 74 94 71 41 53 57  4 71 95 44  1 27 12
 21 28 51 34 51 22 30 14 87 28  0 22 80 13 58 18]
original mean and std are 38.925 and 29.137937040909396
checking whether mean changed or the std changed...
Mean has changed from 38.925 to 43.35
standard deviation has changed
created a numpy array [96 65 76 69 66 55 94  7  9 51]
After processing:
[65 65 69 69 55 55  7  7 51 51]


### Exercise 5 Data types

(1) Create a NumPy array of 10 random integers from 0-100.

(2) Calculate the mean, which will be a float.

(3) Create an array of type float based on it, and replace the
    outliers (i.e., <mean-std or >mean+std) with the mean.

(4) Create a NumPy array of 20 random floats from 0-100.

(5) Replace those numbers whose int portion is even with the mean.
    (So 20.5 would be replaced, but 21.5 would not be.)

In [12]:
a = np.random.randint(0, 101, 10) #1
print(f"Mean of array {a}:\n{a.mean()}") #2

# for #3
b = np.random.normal(loc=a.mean(), scale=a.std(), size=10)
b = np.array([x for x in b if ((x<b.mean()+b.std()) and (x>b.mean()-b.std()))])
print(f"Array \n after replacing outliers:\n{b}")

c = np.random.uniform(low=0.0, high=1000.00000001, size=20) #4

# for #5
mean_of_c = c.mean()
print(f"Mean of array {c} is \n{c.mean()}")
for idx in range(len(c)):
  if int(c[idx])%2==0:
    c[idx] = mean_of_c
print(f"Array after replacing :\n {c}")

Mean of array [75 47  5 86 16 66  2 27 45  9]:
37.8
Array 
 after replacing outliers:
[52.21251445 42.58107166 63.20214828 44.64355867 55.27989806 60.51171146]
Mean of array [613.90488535 367.16447454 634.69115717  73.70895786 520.80343368
 159.28363051 106.54595714 679.86789193 878.95288914 173.70190945
 525.88372375  44.09329445 933.06014759  68.23808698 256.7730699
 583.60277156  11.36043386 519.92962092 903.29723335 378.18026899] is 
421.6521919069138
Array after replacing :
 [613.90488535 367.16447454 421.65219191  73.70895786 421.65219191
 159.28363051 421.65219191 679.86789193 421.65219191 173.70190945
 525.88372375 421.65219191 933.06014759 421.65219191 421.65219191
 583.60277156  11.36043386 519.92962092 903.29723335 421.65219191]


### Exercise 6 nan

(1) Create a NumPy array of 30 random ints from 0-1000.

(2) Find the numbers that are <mean-std or >mean+std, and set them to
    be nan

(3) Now change those nan values to be the mean of the array's
    elements.

In [13]:
a = np.random.randint(0, 101, 10) #1
print(f"array {a}")
a = np.array([np.NaN if ((x<a.mean()+a.std()) and (x>a.mean()-a.std())) else x for x in a]) #2
print(f"array after setting required values with nan:\n {a}")
# for #3
for ids in np.where(np.isnan(a)):
  a[ids] = np.nanmean(a)
print(f"array after setting nan values with mean:\n {a}")

array [ 9 91 69 20 43 97 41  9 42 16]
array after setting required values with nan:
 [ 9. 91. nan nan nan 97. nan  9. nan nan]
array after setting nan values with mean:
 [ 9.  91.  51.5 51.5 51.5 97.  51.5  9.  51.5 51.5]


### Exercise 7 Multidimensional NumPy

(1) Create a 2-dimensional NumPy array of 45 random integers, from 0-100.

(2) Retrieve the elements at row index 2.

(3) Retrieve the elements at column index 3.

(4) Retrieve the elements at row indexes 1 and 4.

(5) Retrieve the elements at column indexes 1 and 4.

(6) Get the mean of the even numbers in row index 4.

(7) Get the mean of the odd numbers in column index 4.

In [14]:
a = np.random.randint(0, 100, [9,5]) #1
print(f"array:\n {a}") 
print(f"the elements at row index 2.: {a[2]}") #2
print(f"the elements at column index 3.: {a[:,3]}") #3
print(f"the elements at row index 1 and 4.: {a[[1,4]]}") #4
print(f"the elements at column index 1 and 4.: {a[:,[1,4]]}") #5
print(f"the mean of the even numbers in row index 4.: {a[4][a[4]%2==0].mean()}") #6
print(f"the mean of the odd numbers in column index 4.: {a[:,4][a[:,4]%2!=0].mean()}") #7

array:
 [[35 13 79 13 11]
 [61 23 69 11  0]
 [51 10 72 63 47]
 [26 59 73 88 30]
 [39 30 25 66  7]
 [26 31 56 47 99]
 [23 24 20 48 87]
 [56 51 62  6 48]
 [85 88 86 60 53]]
the elements at row index 2.: [51 10 72 63 47]
the elements at column index 3.: [13 11 63 88 66 47 48  6 60]
the elements at row index 1 and 4.: [[61 23 69 11  0]
 [39 30 25 66  7]]
the elements at column index 1 and 4.: [[13 11]
 [23  0]
 [10 47]
 [59 30]
 [30  7]
 [31 99]
 [24 87]
 [51 48]
 [88 53]]
the mean of the even numbers in row index 4.: 48.0
the mean of the odd numbers in column index 4.: 50.666666666666664


### Exercise 8 More Multidimensional

(1) Create a 6x6 NumPy array with random integers from 0-100.

(2) What is the mean of each column?

(3) Replace all even numbers in the array with twice their values. (So
    20 will become 40, and 40 will become 80.)

(4) Once again, calculate the mean of each column

(5) Now transpose the array and calculate the mean of each row.  Is it
    the same as you got before?

(6) Now sort each of the columns in the transposed array.  What does
    it look like now?

In [15]:
a = np.random.randint(0, 100, [6,6]) #1
print("array:\n",a)
# for #2
for i in range(6):
  print(f"mean of column index {i}:{a[:,i].mean()}")

print(np.where(a%2==0, a*2, a)) # 3
# for #4
for i in range(6):
  print(f"mean of column index {i}:{a[:,i].mean()}")

# for #5
b = a.T
print(f"transposed array:\n{b}")
for i in range(6):
  print(f"mean of row index {i}:{b[i].mean()}")
  if (a[:,i].mean()==b[i].mean()):
    print(f"mean of row index {i} of transposed array is equal to that of column index {i} of original array\n")
  else:
    print(f"mean of row index {i} of transposed array is not equal to that of column index {i} of original array\n")

# for #6
# 1. Get the argsort indices along each col with axis=0
# 2 . Use indexing to use argsort array for selecting rows i.e. 
#     to index into the first dimension and use another range array to index into the second dimension, 
#     so that it would cover argsort array indices across all the columns
print("after sorting each of the columns in the transposed array:\n", b[b.argsort(axis=0), np.arange(b.argsort(axis=0).shape[1])])

array:
 [[28 54 97 48 45 91]
 [50 84 36  1  6 97]
 [58 46 10 98 68 10]
 [50 86 33  8 60  4]
 [99 96 70  1 43 24]
 [17 26 72 70 57 10]]
mean of column index 0:50.333333333333336
mean of column index 1:65.33333333333333
mean of column index 2:53.0
mean of column index 3:37.666666666666664
mean of column index 4:46.5
mean of column index 5:39.333333333333336
[[ 56 108  97  96  45  91]
 [100 168  72   1  12  97]
 [116  92  20 196 136  20]
 [100 172  33  16 120   8]
 [ 99 192 140   1  43  48]
 [ 17  52 144 140  57  20]]
mean of column index 0:50.333333333333336
mean of column index 1:65.33333333333333
mean of column index 2:53.0
mean of column index 3:37.666666666666664
mean of column index 4:46.5
mean of column index 5:39.333333333333336
transposed array:
[[28 50 58 50 99 17]
 [54 84 46 86 96 26]
 [97 36 10 33 70 72]
 [48  1 98  8  1 70]
 [45  6 68 60 43 57]
 [91 97 10  4 24 10]]
mean of row index 0:50.333333333333336
mean of row index 0 of transposed array is equal to that of column index